config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'static#gossips'
  get 'contact', to: 'static#contact'
  get 'team', to: 'static#team'
  get 'welcome/:first_name', to: 'static#welcome'
  get 'gossip', to: 'static#gossip'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	 has_many :users
end

app/models/goss_tag.rb
class GossTag < ApplicationRecord
	belongs_to :gossip
    belongs_to :tag
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
    has_many :goss_tags, dependent: :destroy
    has_many :tags, through: :goss_tags
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :goss_tags, dependent: :destroy
    has_many :gossips, through: :goss_tags
end

app/models/user.rb
class User < ApplicationRecord
	has_many :gossips, dependent: :destroy
    belongs_to :city
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

	def gossips 
	end

	def contact
	end

	def team
	end

	def welcome
		@first_name = params[:first_name]
	end

	def gossip
		@id = params[:id].to_i
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

<nav class="navbar navbar-expand navbar-dark bg-dark">
  <a class="navbar-brand" href="/">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%=team_path %>">Team <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=contact_path %>">Contact</a>
      </li>
    </ul>
    </form>
  </div>
</nav>
</head>

    <body>

    </body>
    </html>
        <%= yield %>